/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/badge': RouteRecordInfo<'/components/badge', '/components/badge', Record<never, never>, Record<never, never>>,
    '/components/button': RouteRecordInfo<'/components/button', '/components/button', Record<never, never>, Record<never, never>>,
    '/components/color-sheme': RouteRecordInfo<'/components/color-sheme', '/components/color-sheme', Record<never, never>, Record<never, never>>,
    '/components/config-provider': RouteRecordInfo<'/components/config-provider', '/components/config-provider', Record<never, never>, Record<never, never>>,
    '/components/error': RouteRecordInfo<'/components/error', '/components/error', Record<never, never>, Record<never, never>>,
    '/components/hold-button': RouteRecordInfo<'/components/hold-button', '/components/hold-button', Record<never, never>, Record<never, never>>,
    '/components/input': RouteRecordInfo<'/components/input', '/components/input', Record<never, never>, Record<never, never>>,
    '/components/kbd': RouteRecordInfo<'/components/kbd', '/components/kbd', Record<never, never>, Record<never, never>>,
    '/components/link-button': RouteRecordInfo<'/components/link-button', '/components/link-button', Record<never, never>, Record<never, never>>,
    '/components/loading-dots': RouteRecordInfo<'/components/loading-dots', '/components/loading-dots', Record<never, never>, Record<never, never>>,
    '/components/more-button': RouteRecordInfo<'/components/more-button', '/components/more-button', Record<never, never>, Record<never, never>>,
    '/components/progress': RouteRecordInfo<'/components/progress', '/components/progress', Record<never, never>, Record<never, never>>,
    '/components/scrollable': RouteRecordInfo<'/components/scrollable', '/components/scrollable', Record<never, never>, Record<never, never>>,
    '/components/spinner': RouteRecordInfo<'/components/spinner', '/components/spinner', Record<never, never>, Record<never, never>>,
    '/components/stack': RouteRecordInfo<'/components/stack', '/components/stack', Record<never, never>, Record<never, never>>,
    '/components/status-dot': RouteRecordInfo<'/components/status-dot', '/components/status-dot', Record<never, never>, Record<never, never>>,
    '/components/toggle': RouteRecordInfo<'/components/toggle', '/components/toggle', Record<never, never>, Record<never, never>>,
    '/guide': RouteRecordInfo<'/guide', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/installation': RouteRecordInfo<'/guide/installation', '/guide/installation', Record<never, never>, Record<never, never>>,
    '/guide/problems': RouteRecordInfo<'/guide/problems', '/guide/problems', Record<never, never>, Record<never, never>>,
    '/guide/why': RouteRecordInfo<'/guide/why', '/guide/why', Record<never, never>, Record<never, never>>,
  }
}
