// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CButton: typeof import('px-ui/button')['default']
    CCheckbox: typeof import('px-ui/checkbox')['default']
    CIcon: typeof import('px-ui/icon')['default']
    CInput: typeof import('px-ui/input')['default']
    CProvider: typeof import('px-ui/provider')['default']
    CRadio: typeof import('px-ui/radio')['default']
    CSpace: typeof import('px-ui/space')['default']
    CSpinner: typeof import('px-ui/spinner')['default']
    CSwitch: typeof import('px-ui/switch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
