// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CButton: typeof import('./../../../../../carbons/button')['default']
    CInput: typeof import('./../../../../../carbons/input')['default']
    CProvider: typeof import('./../../../../../carbons/provider')['default']
    CSwitch: typeof import('./../../../../../carbons/switch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
